//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarInformation
    {
        public string NumberPlate { get; set; }
        public string VehicleType { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string CarSituation { get; set; }
        public System.DateTime ExitDate { get; set; }
        public decimal Fee { get; set; }
    }
}
