//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Parking_DBEntities3 : DbContext
    {
        public Parking_DBEntities3()
            : base("name=Parking_DBEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarInformation> CarInformations { get; set; }
        public virtual DbSet<OwnerInformation> OwnerInformations { get; set; }
        public virtual DbSet<GeneralInformation> GeneralInformations { get; set; }
    }
}
